//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsProgram.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class informatikexamenEntities : DbContext
    {
        public informatikexamenEntities()
            : base("name=informatikexamenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Email> Email { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<QuestionResponse> QuestionResponse { get; set; }
        public virtual DbSet<Respondent> Respondent { get; set; }
        public virtual DbSet<Response> Response { get; set; }
        public virtual DbSet<RQR> RQR { get; set; }
        public virtual DbSet<RQT> RQT { get; set; }
        public virtual DbSet<UIType> UIType { get; set; }
    }
}
