//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsProgram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespondentDataGood
    {
        public int RespondentId { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public string Language { get; set; }
        public string InternetUse { get; set; }
        public string InternetUseSmart { get; set; }
        public string InternetUseComp { get; set; }
        public Nullable<bool> WebDesign { get; set; }
        public Nullable<decimal> LogInFind { get; set; }
        public Nullable<decimal> LogInClick { get; set; }
        public Nullable<decimal> Qstart { get; set; }
        public Nullable<decimal> TimeFirstQ { get; set; }
        public Nullable<decimal> RQRTime2 { get; set; }
        public Nullable<decimal> RQRTime3 { get; set; }
        public Nullable<decimal> RQRTime4 { get; set; }
        public Nullable<decimal> RQRTime5 { get; set; }
        public Nullable<decimal> RQRTime6 { get; set; }
        public Nullable<decimal> TimeLastRQR { get; set; }
        public Nullable<decimal> RQTTime1 { get; set; }
        public Nullable<decimal> RQTTime2 { get; set; }
        public Nullable<decimal> RQTTime3 { get; set; }
        public string BrowserType { get; set; }
        public string UnitType { get; set; }
    }
}
