//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsProgram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respondent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Respondent()
        {
            this.RQR = new HashSet<RQR>();
            this.RQT = new HashSet<RQT>();
        }
    
        public int Id { get; set; }
        public int UITypeID { get; set; }
        public Nullable<decimal> TotalTime { get; set; }
        public Nullable<decimal> LogInFind { get; set; }
        public Nullable<decimal> LogInClick { get; set; }
        public Nullable<decimal> QStart { get; set; }
        public string BrowserType { get; set; }
    
        public virtual UIType UIType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RQR> RQR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RQT> RQT { get; set; }
    }
}
